server {
    listen 80;

    access_log /dev/stdout;

    location /static/ {
        alias /wger/static/;
        add_header Cache-Control "public, max-age=31536000, immutable" always;
        add_header Vary "Accept-Encoding" always;
    }

    location /media/ {
        alias /wger/media/;
    }
}
